### PR TITLE
added minute interval allowance

### PR DESCRIPTION
**Pull request by dscone**
Love this code...thank you...it has solved and consolidated many things for me.
The one "problem" I had was that running my "cron" every minute was going to be too much.  So, I looked into running it every 10 minutes and having the code detect what should have run within those 10 minutes.

I updated the isDue function to allow an interval of minutes to be checked
so that you would not need to run this function "once per minute" and
could pick up events within the designated interval.  also added tests
to demonstrate usage and check the boundaries.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Having the same issue at the moment, defining a cron as `* * * * *` makes it due _all the time_ instead of every minute. Could this maybe be reconsidered?

**Comment by dragonmantank** [comment]
@Anahkiasen What's the use case that you have that you are running cron more than once per minute? Is this part of a web request as opposed to a command line script?

**Comment by mtdowling** [comment]
I'm still -1 on this because `* * * * * *` should be due every time you ask it because cron is only as granular as seconds.

**Comment by dragonmantank** [comment]
I'm -1 on this right now as well, for a few reasons. My question as to the use case for @Anahkiasen is to better understand how he's using this library, as it seems like there is a better way of handling it outside of this library.

### Only running every 10 minutes

This to me is outside of the scope of this library. `cron-expression` isn't a full cron system, it (to me anyway) is just a system to see if something needs to run. So a cron system uses `cron-expression` to help evaluate a string to see if it needs to run. How often you evaluate the crons should be handled by the application, as @mtdowling mentions above. 

If you don't want `cron-expression` to evaluate all the time, your app just needs to not run it all the time.

### Changing now `* * * * * *` is interpreted

According to the [cron docs](http://www.freebsd.org/cgi/man.cgi?crontab(5)), the smallest granularity is inferred to be 1 minute, because that is the smallest unit that cron can understand. `* * * * * *` is pretty much equal to `*/1 * * * * *` because cron only checks on the minutes.

It's not every second, but if you take a step back `* * * * * *` is technically "run every time that cron runs". This means that any time, cron would report back and say "yes, this command should run." cron-expression should follow that, which it currently does by always evaluating all stars as "run now".

**Comment by Anahkiasen** [comment]
I don't really remember what my issue was but I can tell you at least I fixed it somehow. So I'm guessing it wasn't an issue with the library – can ignore my comment on this one.

**Comment by dragonmantank** [comment]
In that case I'm going to go ahead and close this PR, since timing of actually running `cron-expression` is better left up to the app.

**Pull request closed without merging**
