### PR TITLE
Support for non-hourly offset timezones - refs issues 55 and 76

### PR DESCRIPTION
**Pull request by aGervais**
Great package!

Our project has a requirement to support non-hourly offset timezones ('America/St_Johns' for example) and a colleague of mine has created a fork which resolves the "Impossible CronExpression" issue when using these timezones.

This PR should help resolve:
https://github.com/mtdowling/cron-expression/issues/55
https://github.com/mtdowling/cron-expression/issues/76

Thanks,
Alan

### CODE REVIEW

**Comment by mtdowling** [comment]
This look great. Can you remove all of the extra spacing that was added throughout the PR? I'd like the code base to have a consistent style and not introduce spaces between everything in parenthesis or to line up equal assignments.

**Comment by aGervais** [comment]
Ah yes; saw that as well. No problem; I'll make the change and update this PR.

**Comment by aGervais** [comment]
Updated.

**Comment by DerManoMann** [comment]
I'd wager that this PR also fixes #91...

:+1:

**Pull request merged**
