### PR TITLE
Add php-cs-fixer definition file and styleci.io support

### PR DESCRIPTION
**Pull request by lucasmichot**
And fix code.

---

See https://styleci.io to enable the account

### CODE REVIEW

**Comment by lucasmichot** [comment]
@dragonmantank , I forgot to mention that Styleci is free for public repositories
@GrahamCampbell, creator of Styleci, makes a great support and can help you tune the .styleci.yml file, if required

**Comment by dragonmantank** [comment]
Thanks!

**Comment by lucasmichot** [comment]
@dragonmantank it seems that StyleCI has not been enable though

**Comment by lucasmichot** [comment]
Ping @dragonmantank

**Comment by lucasmichot** [comment]
Ping @mtdowling

**Pull request merged**
