### PR TITLE
[WIP] Ensure Travis will also test for PHP 7

### PR DESCRIPTION
**Pull request by lucasmichot**
Ensure Travis will also test for PHP 7

### CODE REVIEW

**Comment by dragonmantank** [comment]
Can we have this as an allowed failure for now while we sort out the hanging tests for 7?

**Comment by lucasmichot** [comment]
Sure @dragonmantank ;-)

**Comment by GrahamCampbell** [comment]
:-1: for merging.

**Comment by GrahamCampbell** [comment]
While this tests are hanging, this is just a selfish abuse of travis' infrastructure.

**Comment by GrahamCampbell** [comment]
Maybe better to skip the hanging test for now and merge with allowed failures turned off?

**Comment by dragonmantank** [comment]
It's not just travis, it happens locally for me as well. I just haven't had time to diagnose it properly.

**Comment by GrahamCampbell** [comment]
Also, is it possible that this is actually caused by xdebug. Try turning xdebug off on php 7 on travis and see if it works?

**Comment by lucasmichot** [comment]
> Also, is it possible that this is actually caused by xdebug. Try turning xdebug off on php 7 on travis and see if it works?

not xdebug, it also hangs locally

**Comment by lucasmichot** [comment]
@dragonmantank let's keep this PR for the moment

**Comment by lucasmichot** [comment]
The bad guy is https://github.com/mtdowling/cron-expression/blob/master/tests/Cron/CronExpressionTest.php#L170

**Comment by tobias-kuendig** [comment]
See https://github.com/mtdowling/cron-expression/pull/109 for a possible solution.

**Comment by dragonmantank** [comment]
Closing this, since we made PHP 7 mandatory as well as fixed the bug.

**Pull request closed without merging**
