### PR TITLE
Add timezone support

### PR DESCRIPTION
**Pull request by laurencei**
@dragonmantank - as requested - this is a modified version of the https://github.com/mtdowling/cron-expression/pull/115 by @escudeiro.

### CODE REVIEW

**Comment by lioannou** [comment]
I just noticed these tests failed - I'll look into it now

**Comment by lioannou** [comment]
@dragonmantank - ok - all fixed now

**Comment by laurencei** [comment]
@dragonmantank - are we able to get this merged?

Anything you need me to change?

**Comment by dragonmantank** [comment]
Thank you!

**Pull request merged**
